name: pre-commit

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: python -m pip install -r requirements_dev.txt

      - name: Run pre-commit checks
        id: run_pre_commit
        run: pre-commit run --all-files --color always --show-diff-on-failure
        env:
          SKIP: "bentley-file-copyright-check"  # Skip this hook since it is not available from public repo
