name: pre-commit

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run pre-commit
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd  # v3.0.1
        env:
          SKIP: "bentley-file-copyright-check"  # Skip this hook since it is not available from public repo
